[pytest]
# 日志配置
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S

# 测试路径
testpaths = api/tests ui/tests

# 标记
markers =
    smoke: 冒烟测试
    api: 接口测试
    ui: UI测试
    regression: 回归测试

# 禁用Pytest警告
filterwarnings =
    ignore::DeprecationWarning
